#!/usr/bin/env ansible-playbook
---
- name: bootstraps workstation environment
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      action: apt pkg={{ item }} state=present
      sudo: yes
      when: no_sudo is not defined
      with_items:
        - ack-grep
        - apg
        - aptitude
        - ansible

        - build-essential
        - curl
        - git
        - graphviz
        - htop
        - iotop
        - myrepos

        # Haskell stuff
        - cabal-install
        - ghc

        # IRC stuff
        - irssi
        - irssi-scripts

        # SASL auth for irssi
        - libcrypt-blowfish-perl
        - libcrypt-dh-perl
        - libcrypt-openssl-bignum-perl
        - libmath-bigint-perl

        - libreadline-dev
        - libssl-dev
        - nodejs
        - npm

        # Dependencies for apt_repository
        - python-apt
        - python-pycurl

        - tmux
        - wget
        - xclip

    # Install Google Chrome
    - apt_key: id=7FAC5991
               url=https://dl-ssl.google.com/linux/linux_signing_key.pub
      sudo: yes
      when: no_sudo is not defined
    - apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main'
      sudo: yes
      when: no_sudo is not defined
    - apt: pkg=google-chrome-beta
      sudo: yes
      when: no_sudo is not defined

    - name: cabal update
      shell: cabal update

    # Install Turtle and iso8601-time (used by `note`)
    - name: dependencies for note
      shell: cabal install turtle iso8601-time
             creates=~/.cabal/packages/hackage.haskell.org/turtle
